from ursina import *
from ursina.shaders import *
from UrsinaLighting import LitObject


def entities():
    Entity.default_shader = lit_with_shadows_shader
    platform = LitObject(
        model="plane",
        texture="grass",
        scale=Vec3(10, 2, 20),
        position=(-11, 3.5, -4))
    drzewo1 = LitObject(
        model="drzewo",
        texture="drzewo.png",
        scale=2,
        position=(-3, 1, 0))
    drzewo2 = LitObject(
        parent=drzewo1,
        position=(-3, 1, 2))
    szafka = LitObject(
        model="szafka",
        texture="szafka.png",
        collider="box",
        scale=3,
        position=(3, 2, 2.2))
    skybox = Sky(
        model="sphere",
        double_sided=True,
        texture="load",
        rotation=(0, 90, 0))
    biurko = LitObject(
        model="biurko",
        texture="biurko.png",
        collider="box",
        scale=Vec3(2.3, 4, 2.4),
        position=(-3.51, 0.1, -4.7),
        rotation=Vec3(0, 90, 0))
    # biurko.collider = BoxCollider(biurko, size=Vec3(1.2,3,2))
    sciany = LitObject(
        model="sciany",
        texture="sciana.jpg",
        collider="mesh", scale=3,
        position=(.001, 0, .001))
    sufit = LitObject(
        model="sufit",
        texture="sciana.jpg",
        scale=3,
        position=(0, 0, 0),
        collider="mesh")
    lozko = LitObject(
        model="lozko",
        texture="lozko.png",
        collider="mesh",
        scale=1.5,
        position=(-2.7, 0, 1.4),
        rotation=Vec3(0, 90, 0))
    schody = LitObject(
        model="schody",
        texture="schody.png",
        collider="mesh",
        scale=Vec3(1, 0.7, 1),
        position=(4.5, 0.8, -5.6),
        rotation=Vec3(0, 0, 0))
    podloga = LitObject(
        model="podloga",
        texture="podloga.png",
        collider="mesh", scale=3,
        position=(0, 0.01, 0))
    listwa = LitObject(
        model="listwa",
        texture="podloga.png",
        collider="mesh",
        scale=3,
        position=(0, 0, 0))
    latarka = LitObject(
        model="latarka",
        texture="latarka.png",
        collider="box",
        scale=0.3,
        position=(3.76, 2.1, 2.3),
        rotation=Vec3(0, 90, 0))
    krzeslo = LitObject(
        model="krzeslo",
        texture="krzeslo.png",
        collider="mesh",
        scale=2.2,
        position=(-3.5, 0.2, -3.3),
        rotation=Vec3(0, 180, 0))
    okno = LitObject(
        model="okno",
        texture="okno.png",
        collider="mesh",
        scale=3,
        position=(-6.3, 4.6, -3.75))
    drzwi = LitObject(
        model="drzwi",
        texture="drzwi.png",
        collider="mesh",
        scale=Vec3(3, 2.95, 3),
        position=(0, 0.12, 0))
    listwa = LitObject(
        model="listwa2",
        texture="listwa2.png",
        scale=3,
        position=(0, 0, 0),
        collider="mesh")
    klawa = LitObject(
        model="klawa",
        texture="klawa.png",
        scale=0.5,
        position=(-3.4, 1.83, -4.2))
    monitor = LitObject(
        model="monitor",
        texture="monitor.png",
        scale=1.1,
        position=(-3.4, 2.6, -5),
        rotation=Vec3(0, 90, 0))
    komputer = LitObject(
        model="komputer",
        texture="komputer.png",
        scale=0.8,
        position=(-5.3, 2.4, -4.8),
        rotation=Vec3(0, 90, 0))
    lampa = LitObject(
        model="lampa",
        texture="lampa.png",
        scale=1,
        position=(0, 5, -1),
        collider="mesh")
    test = LitObject(
        model='cube',
        color=color.blue,
        scale=1,
        position=(5.91282, 3.33286, -2.2778))
    test.collider = BoxCollider(test, size=(2,2,2))

