from ursina import *
from UrsinaLighting import LitObject, LitSpotLight


platform = LitObject(
    model="plot",
    texture="plot.png",
    scale=1,
    position=(-9, 3.5, -4))
szafka = LitObject(
    model="szafka",
    texture="szafka.png",
    collider="box",
    scale=Vec3(2.4, 3, 2.1),
    position=(5.4, 2, 1),
    rotation=(0, 90, 0))
szafa = LitObject(
    model="szafa",
    texture="szafaa.png",
    collider="box",
    scale=0.7,
    position=(2, 2.5, 2.2),
    rotation=(0, -90, 0),
    normalMap=Texture("assets/png/normal.png"))
skybox = Sky(
    model="sphere",
    double_sided=True,
    texture="load",
    rotation=(0, 90, 0))
biurko = LitObject(
    model="biurko",
    texture="biurko.png",
    collider="box",
    scale=Vec3(2.3, 4, 2.4),
    position=(-3.51, 0.1, -4.7),
    rotation=Vec3(0, 90, 0),
    normalMap=Texture("assets/png/normal.png"))
lozko1 = LitObject(
    model="lozkoC1",
    texture="lozko2.png",
    collider="box",
    scale=1.5,
    position=(-2.7, 0, 1.4),
    rotation=Vec3(0, 90, 0))
lozko2 = LitObject(
    model="lozkoC2",
    texture="lozko1.jpg",
    #collider="box",
    scale=1.5,
    position=(-2.7, 0, 1.4),
    rotation=Vec3(0, 90, 0),
    normalMap=Texture("assets/png/normallozko.jpg"))
drzwigoradoor = LitObject(
    model="drzwiDOOR",
    texture="drzwiOPCL.png",
    collider="mesh",
    scale=Vec3(3, 3.2, 3),
    position=(15.4, 9.9, -8.04),
    rotation=Vec3(0, -90, 0),
    normalMap=Texture("assets/png/normaldoor.jpg"), Color='')
drzwigoraframe = LitObject(
    model="drzwiFRAME",
    texture="drzwiOPCL.png",
    collider="mesh",
    scale=Vec3(3, 3.2, 3),
    position=(15.4, 9.9, -9.24),
    rotation=Vec3(0, -90, 0))
BschodyCOL = LitObject(
    model="BschodyCOL",
    collider="mesh",
    scale=3,
    position=(7.8, 2, -8.2),
    visible=False)
drewniane = LitObject(
    model="drewniane",
    texture="podloga.png",
    collider="mesh", scale=3,
    position=(0, 0, 0),
    normalMap=Texture("assets/png/normal.png"))
betonowe = LitObject(
    model="betonowe",
    texture="sciana.jpg",
    collider="mesh", scale=3,
    position=(0, 0, 0),
    normalMap=Texture("assets/png/normalsciana.jpg"))
sloik1 = LitObject(
    model="sloiki1",
    texture="sloiki1.png",
    #collider="mesh",
    scale=2.98,
    position=(-0.7, 2, -17.16))
sloik2 = LitObject(
    model="sloiki2",
    texture="sloiki2.png",
    #collider="mesh",
    scale=3,
    position=(-0.7, 2, -17.15))
podloga2 = LitObject(
    model="podloga2",
    texture="beton.jpg",
    collider="mesh", scale=3,
    position=(0, 0.23, 0))
krzeslo = LitObject(
    model="krzeslo",
    texture="krzeslo.png",
    collider="box",
    scale=2.2,
    position=(-3.5, 0.2, -3.3),
    rotation=Vec3(0, 180, 0))
okno = LitObject(
    model="okno",
    texture="okno.png",
    collider="mesh",
    scale=3,
    position=(-6.3, 4.6, -3.75))
okno2 = LitObject(
    model="okno",
    texture="okno.png",
    collider="mesh",
    scale=3,
    position=(-6.3, 4.6, -12.75))
drzwiO1frame = LitObject(
    model="drzwiFRAME",
    texture="drzwiOPCL.png",
    #collider="mesh",
    scale=Vec3(3, 3.1, 3),
    position=(4.35, 3.25, -6))
drzwiO1door = LitObject(
    model="drzwiDOOR",
    texture="drzwiOPCL.png",
    collider="mesh",
    scale=Vec3(3, 3.1, 3),
    position=(5.55, 3.25, -6),
    rotation=Vec3(0, 80, 0),
    normalMap=Texture("assets/png/normaldoor.jpg"), Color='')
klawa = LitObject(
    model="klawa",
    texture="klawa.png",
    scale=0.5,
    position=(-3.4, 1.83, -4.2))
monitor = LitObject(
    model="monitor",
    texture="monitor.png",
    scale=1.1,
    position=(-3.4, 2.6, -4.8),
    rotation=Vec3(0, 90, 0))
lampeczka = LitObject(
    model="lampeczka",
    texture="lampeczka.png",
    scale=2,
    position=(-1.7, 2.5, -4.8),
    rotation=Vec3(0, -45, 0))
komputer = LitObject(
    model="komputer",
    texture="komputer.png",
    scale=0.8,
    position=(-5.3, 2.4, -4.8),
    rotation=Vec3(0, 90, 0))
#test = LitObject(
    #model="komputer",
    #texture="komputer.png",
    #scale=0.8,
    #position=(0, 1, 0),
    #rotation=Vec3(0, 90, 0),
    #ambientStrength=8)
lampa = LitObject(
    model="lampa",
    texture="lampa.png",
    scale=1,
    position=(0, 5, -1),
    collider="mesh")
lampa_light = LitSpotLight(
    position=Vec3(0, 5, -1),
    direction=Vec3(0, -1, 0),
    intensity=0,
    range=10,
    angle=50)
kratka = LitObject(
    model="kratka",
    texture="kratka.png",
    collider="mesh",
    scale=3,
    position=(-6.1, 4.6, 1.335))
kratka2 = LitObject(
    model="kratka",
    texture="kratka.png",
    collider="mesh",
    scale=3,
    position=(-6.1, 4.6, -17.8))
szafki = LitObject(
    model="szafki",
    texture="szafka.png",
    collider="box",
    scale=2.9,
    visible=False,
    position=(-0.7, 2, -17.15))
szafki.collider = BoxCollider(szafki, center=Vec3(-1.5, 0, 0.75), size=Vec3(0.5, 1, 3))
szafki = LitObject(
    model="szafki",
    texture="szafka.png",
    collider="box",
    scale=2.9,
    position=(-0.7, 2, -17.15))
drewno = LitObject(
    model="drewno",
    texture="drewno.png",
    collider="box",
    scale=3,
    position=(-2.45, 1.4, -11))
szafki.collider = BoxCollider(szafki, center=Vec3(0, 0, 0), size=Vec3(0.5, 1, 1.5))
rury1 = LitObject(
    model="rury1",
    texture="rury1.png",
    collider="mesh",
    scale=3,
    position=(0.3, 0, -8.1))
rury2 = LitObject(
    model="rury2",
    texture="rury2.png",
    scale=3,
    position=(0.3, 0, -8.1))
kontakt = LitObject(
    model="kontakt",
    texture="kontakt.png",
    collider="box",
    scale=Vec3(1, 1, 1),
    position=(3, 3.5, -5.9),
    isOn=False,
    button=True)
kontakt2 = LitObject(
    model="kontakt",
    texture="kontakt.png",
    collider="mesh",
    scale=1,
    position=(15.3, 10, -7.5),
    rotation=Vec3(0, -90, 0),
    isOn=False)
lampa51 = LitObject(
    model="lampa5",
    texture="lampa5.png",
    scale=1,
    position=(14.3, 12.53, -8))
lampa51_light = LitSpotLight(
    position=Vec3(14.3, 12.53, -8),
    direction=Vec3(0, -1, 0),
    intensity=0,
    range=10,
    angle=50)
lampa52 = LitObject(
    model="lampa5",
    texture="lampa5.png",
    #collider="box",
    scale=1,
    position=(4, 5.9, -8))
lampa52_light = LitSpotLight(
    position=Vec3(4, 5.9, -8),
    direction=Vec3(0, -1, 0),
    intensity=0,
    range=10,
    angle=50)
